### ISSUE TITLE
subprocess

### ISSUE THREAD

**Issue by lingzhenfei123** [zhou13/shapeunity#13]
on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(resume_from)
lzf 20241120-194042-WIN-VC6F7O1KVFI
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "E:\code\shapeunity\train.py", line 205, in <module>
    main()
  File "E:\code\shapeunity\train.py", line 175, in main
    outdir = get_outdir(c, args["--identifier"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\code\shapeunity\train.py", line 53, in get_outdir
    name += "-%s" % git_hash()
                    ^^^^^^^^^^
  File "E:\code\shapeunity\train.py", line 41, in git_hash
    ret = subprocess.check_output(shlex.split(cmd)).strip()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.conda\envs\shapeunity\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\.conda\envs\shapeunity\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'log', '-n', '1', '--pretty=%h']' returned non-zero exit status 128.

**Comment by zhou13** [comment]
Only Linux is supported and you need to install git.
